### ISSUE TITLE
Differents ways to store messages

### ISSUE THREAD

**Issue by PaulFarault** [adaltas/ece-2020-fall-webtech#1]
# Best way to store messages ?
What is the best way to store `messages` object and to link them to a channel ?

The [lab](https://github.com/adaltas/ece-2020-fall-webtech/blob/master/courses/webtech/modules/03.storage/lab.md) mentions that we need to use 3 entities but not how to link them : 
* users
* channels
* messages

Separating the 3 entities would imply to create a loop on all messages for each channel which not seems to be very efficient.

#### Should we work with the same pattern than `channels` ?
``` js
const store = {
  channels: { 
    "my_complicated_channel_uuid" : {
      "name": "channel 1"
    },
    "my_complicated_channel_uuid2" : {
      "name": "channel 2"
    }
    ...
  },
  messages: {
    "my_complicated_message_uuid" : {
      "channel": "my_complicated_channel_uuid", 
      "message": "I'm a message"
    },
    "my_complicated_message_uuid2" : {
      "channel": "my_complicated_channel_uuid", 
      "message": "I'm another message"
    },
    "my_complicated_message_uuid3" : {
      "channel": "my_complicated_channel_uuid2", 
      "message": "I'm yet another message"
    }
    ...
  }
}
```

#### Should we include `messages` directly into `channels` as we aren't using SQL ?
``` js
const store = {
  channels: { 
    "my_complicated_channel_uuid" : {
      "name": "channel 1"
      "messages": [
        "my_complicated_message_uuid" : {"message": "I'm a message"},
        "my_complicated_message_uuid2" : {"message": "I'm another message"},
        ...
      ]
    }
    "my_complicated_channel_uuid2" : {
      "name": "channel 2"
      "messages": [
        "my_complicated_message_uuid" : {"message": "I'm another another message"},
        "my_complicated_message_uuid2" : {"message": "I'm a message too"},
        ...
      ]
    }
    ....
  }
}
```

**Comment by wdavidw** [comment]
SQL has nothing to do in here, let's not involve it.

First, let's ask ourselves what is a message: some data (such as a message) associated with a channel and organized by creation time. Following this definition, there is no need to identify messages by uuid (universally unique identifier). Let's look at your proposals

1. Messages in their own messages object
An object in JavaScript doesn't guarantee the ordering of its elements. Thus, it is not a suitable storage for our messages

2. Messages inside channels
Yes, this looks much better. However, there is a little JavaScript mistake. JavaScript Arrays store elements and not key/value pairs, you just remove the uuids which is not a problem because we don't need them.

Once you start working on LevelDB, you'll ask yourself the same question. A possibility is to use a key like `channel:{channel_uuid}:messages:{creation_timestamp_in_nanoseconds}`

**Comment by PaulFarault** [comment]
Thanks for your answer !

I was making the proposition of using uuid for messages because of this test : 
https://github.com/adaltas/ece-2020-fall-webtech/blob/598cc1226cc3313d36dd9ebc331c405cd3078d4e/courses/webtech/modules/03.storage/lab/test/messages.js#L23-L40

Would my code pass the test without using uuid or should I adapt the test ?

(Also, do I need to "close" this issue ?)

**Comment by wdavidw** [comment]
Remember that at the time you write your tests, you are not yet confronted with the reality of the code/implementation. I've made some changes, replacing message.uuid with messages.creation. It doesn't mean the tests are final, adjustments will be made if necessary.
