### ISSUE TITLE
Lab6 - OAuth2

### ISSUE THREAD

**Issue by fond92** [adaltas/ece-2020-fall-webtech#5]
ISSUE TO REPORT : 
-----

 + Firstly, when using the `openid-cli-usage` app, in `--help` the command I have to create the URL is called `url` ​and not `redirect_url` as in your article. Nevertheless, they both work the same way so that is just a small adjustement to make. Still, I am curious to know wheater it is normal or not. I just git-cloned the Github repository and made npm install and launched it. (I reproduced these same steps on a Linux Ubuntu VM and got the same url command)

 + Secondly, the code provided in the 2nd step of the artic​le doesn't work on a copy-paste basis. In fact, the `client_secret` option you provide is incorrect. Assuming we are using the Dex example-app, the `client_secret` is `ZXhhbXBsZS1hcHAtc2VjcmV0` . I suppose it was maybe just a typo but that could be worth a change in your article.

 + Thirdly, when I remove the `--client_secret` option I had an error telling me that this is required, but when I launch the Node.js module directly with `npx cofffee ./lib/2.code_grant.coffee` it works proprely."

---
Thank you

**Comment by wdavidw** [comment]
Good points.

Number 1 and 3 are because I didn't release the lastest version on the NPM registry, it is online now. In number 2, client_secret are meant to be customized with user settings but you are right, they must be consistent. The article is updated as well.

Note, the `npx` command cache the application, if you still see the `url` option instead of `redirect_url` when running `npx openid-cli-usage help`, you are still using the old version. I didn't find a better solution than removing the all NPM local dir with `rm -rf ~/.npm`, not very nice I admit.
